/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20012Dest;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Détail de chaque courrier de cet envoi
 */
@Schema(description = "Détail de chaque courrier de cet envoi")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-30T14:41:58.166575150Z[GMT]")

public class InlineResponse20012Detail {
  @SerializedName("refCourrier")
  private String refCourrier = null;

  @SerializedName("dest")
  private InlineResponse20012Dest dest = null;

  public InlineResponse20012Detail refCourrier(String refCourrier) {
    this.refCourrier = refCourrier;
    return this;
  }

   /**
   * Référence Merci facteur du courrier, si&#x3D;null alors le courrier n&#x27;est pas encore généré (cf. statut de l&#x27;envoi)
   * @return refCourrier
  **/
  @Schema(description = "Référence Merci facteur du courrier, si=null alors le courrier n'est pas encore généré (cf. statut de l'envoi)")
  public String getRefCourrier() {
    return refCourrier;
  }

  public void setRefCourrier(String refCourrier) {
    this.refCourrier = refCourrier;
  }

  public InlineResponse20012Detail dest(InlineResponse20012Dest dest) {
    this.dest = dest;
    return this;
  }

   /**
   * Get dest
   * @return dest
  **/
  @Schema(description = "")
  public InlineResponse20012Dest getDest() {
    return dest;
  }

  public void setDest(InlineResponse20012Dest dest) {
    this.dest = dest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012Detail inlineResponse20012Detail = (InlineResponse20012Detail) o;
    return Objects.equals(this.refCourrier, inlineResponse20012Detail.refCourrier) &&
        Objects.equals(this.dest, inlineResponse20012Detail.dest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refCourrier, dest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012Detail {\n");
    
    sb.append("    refCourrier: ").append(toIndentedString(refCourrier)).append("\n");
    sb.append("    dest: ").append(toIndentedString(dest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
