/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20010AffranchissementPAYS;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * object avec, pour chaque pays demandé, le montant de l&#x27;affranchissement et la zone géographique
 */
@Schema(description = "object avec, pour chaque pays demandé, le montant de l'affranchissement et la zone géographique")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-30T14:41:58.166575150Z[GMT]")

public class InlineResponse20010Affranchissement {
  @SerializedName("PAYS")
  private InlineResponse20010AffranchissementPAYS PAYS = null;

  public InlineResponse20010Affranchissement PAYS(InlineResponse20010AffranchissementPAYS PAYS) {
    this.PAYS = PAYS;
    return this;
  }

   /**
   * Get PAYS
   * @return PAYS
  **/
  @Schema(description = "")
  public InlineResponse20010AffranchissementPAYS getPAYS() {
    return PAYS;
  }

  public void setPAYS(InlineResponse20010AffranchissementPAYS PAYS) {
    this.PAYS = PAYS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010Affranchissement inlineResponse20010Affranchissement = (InlineResponse20010Affranchissement) o;
    return Objects.equals(this.PAYS, inlineResponse20010Affranchissement.PAYS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PAYS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010Affranchissement {\n");
    
    sb.append("    PAYS: ").append(toIndentedString(PAYS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
