/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Résumé du contenu de l&#x27;envoi
 */
@Schema(description = "Résumé du contenu de l'envoi")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-11T10:32:30.069126169Z[GMT]")

public class InlineResponse2009Resume {
  @SerializedName("nb_dest")
  private Integer nbDest = null;

  @SerializedName("nb_page")
  private Integer nbPage = null;

  public InlineResponse2009Resume nbDest(Integer nbDest) {
    this.nbDest = nbDest;
    return this;
  }

   /**
   * Nombre de destinataires (&#x3D; nombre de courriers générés)
   * @return nbDest
  **/
  @Schema(description = "Nombre de destinataires (= nombre de courriers générés)")
  public Integer getNbDest() {
    return nbDest;
  }

  public void setNbDest(Integer nbDest) {
    this.nbDest = nbDest;
  }

  public InlineResponse2009Resume nbPage(Integer nbPage) {
    this.nbPage = nbPage;
    return this;
  }

   /**
   * Nombre de page(s) décomptées(s) par destinataire
   * @return nbPage
  **/
  @Schema(description = "Nombre de page(s) décomptées(s) par destinataire")
  public Integer getNbPage() {
    return nbPage;
  }

  public void setNbPage(Integer nbPage) {
    this.nbPage = nbPage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2009Resume inlineResponse2009Resume = (InlineResponse2009Resume) o;
    return Objects.equals(this.nbDest, inlineResponse2009Resume.nbDest) &&
        Objects.equals(this.nbPage, inlineResponse2009Resume.nbPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nbDest, nbPage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2009Resume {\n");
    
    sb.append("    nbDest: ").append(toIndentedString(nbDest)).append("\n");
    sb.append("    nbPage: ").append(toIndentedString(nbPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
