/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2009PriceTotal
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-11T10:32:30.069126169Z[GMT]")

public class InlineResponse2009PriceTotal {
  @SerializedName("ht")
  private String ht = null;

  @SerializedName("ttc")
  private String ttc = null;

  public InlineResponse2009PriceTotal ht(String ht) {
    this.ht = ht;
    return this;
  }

   /**
   * Montant total HT
   * @return ht
  **/
  @Schema(description = "Montant total HT")
  public String getHt() {
    return ht;
  }

  public void setHt(String ht) {
    this.ht = ht;
  }

  public InlineResponse2009PriceTotal ttc(String ttc) {
    this.ttc = ttc;
    return this;
  }

   /**
   * Montant total TTC
   * @return ttc
  **/
  @Schema(description = "Montant total TTC")
  public String getTtc() {
    return ttc;
  }

  public void setTtc(String ttc) {
    this.ttc = ttc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2009PriceTotal inlineResponse2009PriceTotal = (InlineResponse2009PriceTotal) o;
    return Objects.equals(this.ht, inlineResponse2009PriceTotal.ht) &&
        Objects.equals(this.ttc, inlineResponse2009PriceTotal.ttc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ht, ttc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2009PriceTotal {\n");
    
    sb.append("    ht: ").append(toIndentedString(ht)).append("\n");
    sb.append("    ttc: ").append(toIndentedString(ttc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
