/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Objet contenant la correspondance entre chaque code d&#x27;erreur et sa signification.
 */
@Schema(description = "Objet contenant la correspondance entre chaque code d'erreur et sa signification.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-30T14:41:58.166575150Z[GMT]")

public class InlineResponse20020ListErrors {
  @SerializedName("ERROR_CODE_1")
  private String erRORCODE1 = null;

  @SerializedName("ERROR_CODE_2")
  private String erRORCODE2 = null;

  @SerializedName("ERROR_CODE_3")
  private String erRORCODE3 = null;

  @SerializedName("ETC")
  private String ETC = null;

  public InlineResponse20020ListErrors erRORCODE1(String erRORCODE1) {
    this.erRORCODE1 = erRORCODE1;
    return this;
  }

   /**
   * Sigification de ce code d&#x27;erreur
   * @return erRORCODE1
  **/
  @Schema(description = "Sigification de ce code d'erreur")
  public String getErRORCODE1() {
    return erRORCODE1;
  }

  public void setErRORCODE1(String erRORCODE1) {
    this.erRORCODE1 = erRORCODE1;
  }

  public InlineResponse20020ListErrors erRORCODE2(String erRORCODE2) {
    this.erRORCODE2 = erRORCODE2;
    return this;
  }

   /**
   * Sigification de ce code d&#x27;erreur
   * @return erRORCODE2
  **/
  @Schema(description = "Sigification de ce code d'erreur")
  public String getErRORCODE2() {
    return erRORCODE2;
  }

  public void setErRORCODE2(String erRORCODE2) {
    this.erRORCODE2 = erRORCODE2;
  }

  public InlineResponse20020ListErrors erRORCODE3(String erRORCODE3) {
    this.erRORCODE3 = erRORCODE3;
    return this;
  }

   /**
   * Sigification de ce code d&#x27;erreur
   * @return erRORCODE3
  **/
  @Schema(description = "Sigification de ce code d'erreur")
  public String getErRORCODE3() {
    return erRORCODE3;
  }

  public void setErRORCODE3(String erRORCODE3) {
    this.erRORCODE3 = erRORCODE3;
  }

  public InlineResponse20020ListErrors ETC(String ETC) {
    this.ETC = ETC;
    return this;
  }

   /**
   * etc.
   * @return ETC
  **/
  @Schema(description = "etc.")
  public String getETC() {
    return ETC;
  }

  public void setETC(String ETC) {
    this.ETC = ETC;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20020ListErrors inlineResponse20020ListErrors = (InlineResponse20020ListErrors) o;
    return Objects.equals(this.erRORCODE1, inlineResponse20020ListErrors.erRORCODE1) &&
        Objects.equals(this.erRORCODE2, inlineResponse20020ListErrors.erRORCODE2) &&
        Objects.equals(this.erRORCODE3, inlineResponse20020ListErrors.erRORCODE3) &&
        Objects.equals(this.ETC, inlineResponse20020ListErrors.ETC);
  }

  @Override
  public int hashCode() {
    return Objects.hash(erRORCODE1, erRORCODE2, erRORCODE3, ETC);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20020ListErrors {\n");
    
    sb.append("    erRORCODE1: ").append(toIndentedString(erRORCODE1)).append("\n");
    sb.append("    erRORCODE2: ").append(toIndentedString(erRORCODE2)).append("\n");
    sb.append("    erRORCODE3: ").append(toIndentedString(erRORCODE3)).append("\n");
    sb.append("    ETC: ").append(toIndentedString(ETC)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
