/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20018QuotasCredit;
import io.swagger.client.model.InlineResponse20018QuotasPages;
import io.swagger.client.model.InlineResponse20018QuotasPlan;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Objet contenant les infos des quotas du compte.
 */
@Schema(description = "Objet contenant les infos des quotas du compte.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-30T14:41:58.166575150Z[GMT]")

public class InlineResponse20018Quotas {
  @SerializedName("plan")
  private InlineResponse20018QuotasPlan plan = null;

  @SerializedName("credit")
  private InlineResponse20018QuotasCredit credit = null;

  @SerializedName("pages")
  private InlineResponse20018QuotasPages pages = null;

  public InlineResponse20018Quotas plan(InlineResponse20018QuotasPlan plan) {
    this.plan = plan;
    return this;
  }

   /**
   * Get plan
   * @return plan
  **/
  @Schema(description = "")
  public InlineResponse20018QuotasPlan getPlan() {
    return plan;
  }

  public void setPlan(InlineResponse20018QuotasPlan plan) {
    this.plan = plan;
  }

  public InlineResponse20018Quotas credit(InlineResponse20018QuotasCredit credit) {
    this.credit = credit;
    return this;
  }

   /**
   * Get credit
   * @return credit
  **/
  @Schema(description = "")
  public InlineResponse20018QuotasCredit getCredit() {
    return credit;
  }

  public void setCredit(InlineResponse20018QuotasCredit credit) {
    this.credit = credit;
  }

  public InlineResponse20018Quotas pages(InlineResponse20018QuotasPages pages) {
    this.pages = pages;
    return this;
  }

   /**
   * Get pages
   * @return pages
  **/
  @Schema(description = "")
  public InlineResponse20018QuotasPages getPages() {
    return pages;
  }

  public void setPages(InlineResponse20018QuotasPages pages) {
    this.pages = pages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20018Quotas inlineResponse20018Quotas = (InlineResponse20018Quotas) o;
    return Objects.equals(this.plan, inlineResponse20018Quotas.plan) &&
        Objects.equals(this.credit, inlineResponse20018Quotas.credit) &&
        Objects.equals(this.pages, inlineResponse20018Quotas.pages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plan, credit, pages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20018Quotas {\n");
    
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    credit: ").append(toIndentedString(credit)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
