/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetTokenApi
 */
@Ignore
public class GetTokenApiTest {

    private final GetTokenApi api = new GetTokenApi();

    /**
     * Obtenir un access token
     *
     * IMPORTANT :   - Ne demander un access token qu&#x27;une seule fois par tranche de 24h. Après execution de getToken, stockez en local l&#x27;access token obtenu et refaites une demande lorsqu&#x27;il est expiré.  - Ne jamais faire transiter votre Secret Key non hashée.  [&#x60;En savoir plus sur le hashage de la private key&#x60;](https://github.com/MerciFacteur/Merci-facteur-API/tree/master/hash-secret-key)
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTokenTest() throws Exception {
        String wwServiceSignature = null;
        String wwTimestamp = null;
        String wwServiceId = null;
        String wwAuthorizedIp = null;
        InlineResponse200 response = api.getToken(wwServiceSignature, wwTimestamp, wwServiceId, wwAuthorizedIp);

        // TODO: test validations
    }
}
